#!/usr/bin/env python3
"""Entry point for mcce-chat CLI."""

import sys
from os.path import dirname, realpath

_BIN_DIR = dirname(realpath(__file__))
_ROOT_DIR = dirname(_BIN_DIR)
sys.path.insert(0, _BIN_DIR)

from mcce_chat.cli import main

if __name__ == "__main__":
    main(root_dir=_ROOT_DIR)
else:
    main(root_dir=_ROOT_DIR)
